### ISSUE TITLE
Swerve code missing !!!!

### ISSUE THREAD

**Issue by crismariudenis** [KookyBotz/CenterStage#2]
The code for the swerve drive is missing.

**Comment by ProDCG** [comment]
sir on behalf of the AntiOpenSourceOrganization, make your own damn swerve code idiot (just kidding, love you denis, cyliis is the best)

**Comment by crismariudenis** [comment]
![kissyfishu](https://github.com/KookyBotz/CenterStage/assets/78813212/9913abbf-dab8-4e05-bc53-452cb61dbf11)
